# Generated by Django 5.2.3 on 2025-06-19 08:58

import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=100, null=True)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('send', 'Отправка'), ('receive', 'Получение')], max_length=10)),
                ('waybill_photo', models.ImageField(blank=True, null=True, upload_to='waybills/')),
                ('product_photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('waybill_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('created', 'Создано'), ('processing', 'В обработке'), ('transit', 'В пути'), ('delivered', 'Доставлено'), ('problem', 'Проблема')], default='created', max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('telegram_waybill_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_product_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('PROFILE_UPDATE', 'Обновление профиля'), ('PASSWORD_CHANGE', 'Смена пароля'), ('AVATAR_CHANGE', 'Смена аватара'), ('SHIPMENT_CREATE', 'Создание отправки'), ('SHIPMENT_UPDATE', 'Обновление отправки'), ('SHIPMENT_DELETE', 'Удаление отправки'), ('SHIPMENT_STATUS', 'Изменение статуса отправки'), ('SHIPMENT_VIEW', 'Просмотр отправки'), ('2FA_TOGGLE', 'Изменение 2FA')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity',
                'verbose_name_plural': 'User Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
